CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TelegramId" bigint NOT NULL,
    "Username" character varying(255) NOT NULL,
    "FirstName" character varying(255) NOT NULL,
    "LastName" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Events" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatorId" integer NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    "EventDate" timestamp with time zone NOT NULL,
    "Location" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Events_Users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserAvailabilities" (
    "UserId" integer NOT NULL,
    "AvailableDate" timestamp with time zone NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    CONSTRAINT "PK_UserAvailabilities" PRIMARY KEY ("UserId", "AvailableDate"),
    CONSTRAINT "FK_UserAvailabilities_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EventDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "UploadedBy" integer NOT NULL,
    "FilePath" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EventDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EventDocuments_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EventDocuments_Users_UploadedBy" FOREIGN KEY ("UploadedBy") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "LLMGeneratedPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "GeneratedBy" integer NOT NULL,
    "PlanText" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LLMGeneratedPlans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LLMGeneratedPlans_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LLMGeneratedPlans_Users_GeneratedBy" FOREIGN KEY ("GeneratedBy") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Participants" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Participants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Participants_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Participants_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "AssignedTo" integer,
    "Title" character varying(255) NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItems_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_Users_AssignedTo" FOREIGN KEY ("AssignedTo") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Votes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "VoteOption" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Votes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Votes_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Votes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_EventDocuments_EventId" ON "EventDocuments" ("EventId");

CREATE INDEX "IX_EventDocuments_UploadedBy" ON "EventDocuments" ("UploadedBy");

CREATE INDEX "IX_Events_CreatorId" ON "Events" ("CreatorId");

CREATE INDEX "IX_LLMGeneratedPlans_EventId" ON "LLMGeneratedPlans" ("EventId");

CREATE INDEX "IX_LLMGeneratedPlans_GeneratedBy" ON "LLMGeneratedPlans" ("GeneratedBy");

CREATE INDEX "IX_Participants_EventId" ON "Participants" ("EventId");

CREATE INDEX "IX_Participants_UserId" ON "Participants" ("UserId");

CREATE INDEX "IX_TaskItems_AssignedTo" ON "TaskItems" ("AssignedTo");

CREATE INDEX "IX_TaskItems_EventId" ON "TaskItems" ("EventId");

CREATE UNIQUE INDEX "IX_Users_TelegramId" ON "Users" ("TelegramId");

CREATE INDEX "IX_Votes_EventId" ON "Votes" ("EventId");

CREATE INDEX "IX_Votes_UserId" ON "Votes" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250306202531_InitialCreate', '9.0.2');

ALTER TABLE "Votes" ADD "Type" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250312172207_AddVoteType', '9.0.2');

ALTER TABLE "Events" ALTER COLUMN "Location" TYPE text;
ALTER TABLE "Events" ALTER COLUMN "Location" DROP NOT NULL;

ALTER TABLE "Events" ALTER COLUMN "EventDate" DROP NOT NULL;

ALTER TABLE "Events" ADD "TelegramChatId" bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250312194101_UpdateUserAndEventModels', '9.0.2');

ALTER TABLE "Events" ADD "PlaceVotingId" integer;

ALTER TABLE "Events" ADD "TimeVotingId" integer;

CREATE TABLE "Votings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "Options" text[] NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Votings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Votings_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Events_PlaceVotingId" ON "Events" ("PlaceVotingId");

CREATE UNIQUE INDEX "IX_Events_TimeVotingId" ON "Events" ("TimeVotingId");

CREATE INDEX "IX_Votings_EventId" ON "Votings" ("EventId");

ALTER TABLE "Events" ADD CONSTRAINT "FK_Events_Votings_PlaceVotingId" FOREIGN KEY ("PlaceVotingId") REFERENCES "Votings" ("Id") ON DELETE SET NULL;

ALTER TABLE "Events" ADD CONSTRAINT "FK_Events_Votings_TimeVotingId" FOREIGN KEY ("TimeVotingId") REFERENCES "Votings" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250314141908_AddVotingModel', '9.0.2');

ALTER TABLE "Votes" DROP CONSTRAINT "FK_Votes_Events_EventId";

ALTER TABLE "Votes" ALTER COLUMN "EventId" DROP NOT NULL;

ALTER TABLE "Votes" ADD "VoteId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Votes" ADD "VotingId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Votes_VotingId" ON "Votes" ("VotingId");

ALTER TABLE "Votes" ADD CONSTRAINT "FK_Votes_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id");

ALTER TABLE "Votes" ADD CONSTRAINT "FK_Votes_Votings_VotingId" FOREIGN KEY ("VotingId") REFERENCES "Votings" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250314150745_ChangeVoteRelations', '9.0.2');

ALTER TABLE "Events" DROP CONSTRAINT "FK_Events_Votings_PlaceVotingId";

ALTER TABLE "Events" DROP CONSTRAINT "FK_Events_Votings_TimeVotingId";

ALTER TABLE "Votes" DROP CONSTRAINT "FK_Votes_Votings_VotingId";

DROP TABLE "Votings";

CREATE TABLE "Polls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "Options" text[] NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Polls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Polls_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Polls_EventId" ON "Polls" ("EventId");

ALTER TABLE "Events" ADD CONSTRAINT "FK_Events_Polls_PlaceVotingId" FOREIGN KEY ("PlaceVotingId") REFERENCES "Polls" ("Id") ON DELETE SET NULL;

ALTER TABLE "Events" ADD CONSTRAINT "FK_Events_Polls_TimeVotingId" FOREIGN KEY ("TimeVotingId") REFERENCES "Polls" ("Id") ON DELETE SET NULL;

ALTER TABLE "Votes" ADD CONSTRAINT "FK_Votes_Polls_VotingId" FOREIGN KEY ("VotingId") REFERENCES "Polls" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250317013135_ChangeVotingToPoll', '9.0.2');

ALTER TABLE "Votes" DROP CONSTRAINT "FK_Votes_Polls_VotingId";

ALTER TABLE "Votes" RENAME COLUMN "VotingId" TO "PollId";

ALTER INDEX "IX_Votes_VotingId" RENAME TO "IX_Votes_PollId";

ALTER TABLE "Votes" ADD CONSTRAINT "FK_Votes_Polls_PollId" FOREIGN KEY ("PollId") REFERENCES "Polls" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250317015922_ChangeFieldsNames', '9.0.2');

COMMIT;


